# Etapa 1: construir React
FROM node:22-alpine AS build

WORKDIR /app

COPY package*.json ./

RUN npm ci

COPY . .

RUN npm run build


# Etapa 2: servir React con Nginx
FROM nginx:alpine

COPY --from=build /app/dist /usr/share/nginx/html

# Configuración para React Router
COPY nginx/default.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
